### PR TITLE
Allow user to control timeout notice by adding flag

### PR DESCRIPTION
**Pull request by liwanglin12**

### CODE REVIEW

**Comment by blueset** [comment]
It would be better if it can be an `int` flag that controls the frequency, where 0 can be the option to turn off such messages, but it's up to you if you feel like to have a boolean instead.

Please also add your new config entry to the documentation.

**Comment by liwanglin12** [comment]
OK. It's done!

**Comment by liwanglin12** [comment]
置0的话怕是会报错吧。。。

**Comment by blueset** [comment]
[放了大于等于 0](https://github.com/blueset/ehForwarderBot/pull/91/files#diff-5d65b6f95d32c785286fec609c988569R1609)

```python
            timeout_interval = self._flag("timeout_interval", 10)
            if timeout_interval > 0 and self.timeout_count % timeout_interval == 0:
                # ...
```

**Comment by liwanglin12** [comment]
发现了，贼尴尬（

**Pull request merged**
