### PR TITLE
Add proxy to telegram plugin.

### PR DESCRIPTION
**Pull request by Catofes**
Sometime when I need wechat and telegram work together, I prefer to put the server in China and add an proxy to telegram. So I add an option to set proxy for telegram_master_plugin.

### CODE REVIEW

**Comment by vjdsnagiurt** [comment]
我也需要这个功能，请问如何使用代理呢？把

> `"proxy": "" `

改成下面这样？

> `"proxy": "socks5:127.0.0.1:1080"`

**Comment by Catofes** [comment]
@vjdsnagiurt  https://github.com/python-telegram-bot/python-telegram-bot/issues/525

**Comment by blueset** [comment]
All optional parameters should be able to be omitted without crashing. Detect it with `_flag` or add a fallback mechanism.

Please also add your new config entry to the documentation.

**Comment by RoyXiang** [comment]
python-telegram-bot adds support for sock5 proxy since [v6.0.0](https://github.com/python-telegram-bot/python-telegram-bot/releases/tag/v6.0.0). The only thing needed is to set a correct `HTTPS_PROXY` environment variable and install `PySocks` module.

**Comment by liwanglin12** [comment]
@RoyXiang if I set this env var, all programs may use this. I can't accept this.

**Pull request closed without merging**
